app/blueprints/collect/models.py
from datetime import datetime
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(db.Model, UserMixin):
    id= db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, nullable=True)
    email = db.Column(db.String(120), unique=True, nullable=True)
    password_hash = db.Column(db.String(120), nullable=True)
    collect = db.relationship('CollectedPokemon', backref='author', lazy='dynamic')

    def __repr__(self):
        return f"<User: {self.username}>"
    def __str__(self):
        return f'User: {self.email}|{self.username}'
    
    def hash_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    
    def commit(self):
        db.session.add(self)
        db.session.commit()

class CollectedPokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    pokemon = db.Column(db.String(40))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Email


class PokemonPicker(FlaskForm):

    pokemon = StringField('Pokemon Name or ID Number(1-1008)', validators=[DataRequired()])
    submit = SubmitField('Submit')
    collect_card = SubmitField('Collect')
    

class RegisterForm(FlaskForm):
    
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message='Password must match')])
    submit = SubmitField('Register') 
            
class SignInForm(FlaskForm):

    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField("Sign In")        

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_cors import CORS

cors = CORS()
db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()

app = Flask(__name__)
app.config.from_object(Config)

db.init_app(app)
migrate.init_app(app, db)
login.init_app(app)
cors.init_app(app)

login.login_view = '/sign_in'
login.login_message = 'Make sure you login'

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app.blueprints.collect import bp as collect_bp
app.register_blueprint(collect_bp)

from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    
    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    cors.init_app(app)

    login.login_view = '/sign_in'
    login.login_message = 'Make sure you login'

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.collect import bp as collect_bp
    app.register_blueprint(collect_bp)

    from app.blueprints.api import bp as api_bp
    app.register_blueprint(api_bp)

    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import routes

app/blueprints/api/routes.py
from . import bp as api_bp
from app.blueprints.collect.models import CollectedPokemon

@api_bp.route('/collect')
def api_cards():
    result = []
    collection = CollectedPokemon.query.all()
    for card in collection:
        result.append({
            'id': card.id,
            'pokemon': card.pokemon,
            'timestamp': card.timestamp,
            'user_id': card.user_id
        })
    return result

@api_bp.route('/collect/<id>', methods=['GET'])
def api_card(id):
    card = CollectedPokemon.query.get(int(id))
    return {
            'id': card.id,
            'pokemon': card.pokemon,
            'timestamp': card.timestamp,
            'user_id': card.user_id
        }

app/blueprints/collect/__init__.py
from flask import Blueprint

bp = Blueprint('collect', __name__, url_prefix='/collect')

from . import routes, models

app/blueprints/collect/routes.py
from . import bp as collect_bp
from flask import render_template, redirect, url_for
import requests
from app.forms import PokemonPicker
from flask_login import login_required, current_user
from .models import User, CollectedPokemon


user_input = []
@collect_bp.route('/pokemon', methods=['GET', 'POST'])
@login_required
def pick_pokemon():
    poke = PokemonPicker()
    pokemon = poke.pokemon.data
    if poke.validate_on_submit():
        user_input.clear() 
        req = requests.get(f'https://pokeapi.co/api/v2/pokemon/{pokemon}')
        data = req.json()
        
        user_input.append(data['name'])
        
        abilities = data['abilities']
        abilities = list(map(lambda x: x['ability']['name'], abilities))
    
        types = data['types']
        types = list(map(lambda x: x['type']['name'], types))
    
        stats = data['stats']
        stats = list(map(lambda x: x['stat']['name'], stats))
    
        base_stat = data['stats']
        base_stat = list(map(lambda x: x['base_stat'], base_stat))
        return render_template('collect.jinja', poke=poke, data=data, abilities=abilities, types=types, stats=stats, base_stat=base_stat)  
    
    return render_template('collect.jinja', poke=poke)

@collect_bp.route('/user/<username>')
def user(username):
    user_match = User.query.filter_by(username=username).first()
    if not user_match:
        redirect('/')
    collect = user_match.collect
    return render_template('user.jinja', user=user_match, collect=collect)

@collect_bp.route('/collect', methods=['GET', 'POST'])
def collect_card():
    poke = PokemonPicker()
    pokemon = user_input[0]
    card = CollectedPokemon(pokemon=pokemon, user_id=current_user.id)
    card.commit()
    return render_template('collect.jinja', poke=poke)

@collect_bp.route('/collect/<pokemon>,<username>', methods=['GET', 'POST'])
def show_card(pokemon, username):
    user_match = User.query.filter_by(username=username).first()
    if not user_match:
        redirect('/')
    collect = user_match.collect
    req = requests.get(f'https://pokeapi.co/api/v2/pokemon/{pokemon}')
    data = req.json()
    
    
    abilities = data['abilities']
    abilities = list(map(lambda x: x['ability']['name'], abilities))

    types = data['types']
    types = list(map(lambda x: x['type']['name'], types))

    stats = data['stats']
    stats = list(map(lambda x: x['stat']['name'], stats))

    base_stat = data['stats']
    base_stat = list(map(lambda x: x['base_stat'], base_stat))
    return render_template('user.jinja', user=user_match, collect=collect, data=data, abilities=abilities, types=types, stats=stats, base_stat=base_stat)

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import routes

app/blueprints/main/routes.py
from . import bp as main_bp
from flask import render_template

@main_bp.route('/')
def index():
    return render_template('index.jinja')

@main_bp.route('/about')
def about():
    return render_template('about.jinja')

app/templates/about.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Pick Your Pokemon</h2>
    
{% endblock content %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body class="container mt-5" >
    {% include 'navbar.jinja' %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <h1>Pokemon Collect Them All</h1>
    {% if current_user.is_active %}
        <p>{{ current_user.username }}</p>
    {% endif %}
    {% block content %}

    {% endblock content %}
</body>
</html>

app/templates/collect.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Pick Your Pokemon</h2>
    <form action="{{ url_for('collect.pick_pokemon') }}" method="post">
        {{ poke.hidden_tag() }}
        <p>
            {{ poke.pokemon.label }} <br>
            {{ poke.pokemon(size=32) }}
        </p>
        <p>
            {{ poke.submit(class='btn btn-primary') }}
        </p> 
        
        {% if data %}  
        <div class="card" style="width: 18rem;">
        <img src="{{ data['sprites']['front_default'] }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ data['name'] }}</h5>
                <p class="card-text">Type: {{ data['types'][0]['type']['name'] }} {% if data['types'][1] %}, {{  data['types'][1]['type']['name'] }} {% else %}  {% endif %}<br>
                                    Abilities: {{ abilities[0] }}, {{ abilities[1] }} <br>
                                    Stats: <br>
                                    {{ stats[0] }}: {{ base_stat[0] }} <br>
                                    {{ stats[1] }}: {{ base_stat[1] }} <br>
                                    {{ stats[2] }}: {{ base_stat[2] }} <br>
                                    {{ stats[3] }}: {{ base_stat[3] }} <br>
                                    {{ stats[4] }}: {{ base_stat[4] }} <br>
                                    {{ stats[5] }}: {{ base_stat[5] }}</p>
                <a href="{{ url_for('collect.collect_card') }}" class="btn btn-primary">Collect</a>
            </div>
        </div>
        {% endif %}
    </form>
{% endblock content %}

app/templates/index.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Sign In and Start Your Own Collection</h2>
    
{% endblock content %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Pokemon Collector</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
        <a class="nav-link"  href="{{ url_for('main.about') }}">About</a>
        {% if current_user.is_active %}
        <a class="nav-link"  href="{{ url_for('collect.user', username=current_user.username) }}">Collection</a>
        <a class="nav-link"  href="{{ url_for('collect.pick_pokemon') }}">Pokemon Cards</a>
        <a class="nav-link"  href="{{ url_for('auth.sign_out') }}">Sign Out</a>
        {% else %}
        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        <a class="nav-link" href="{{ url_for('auth.sign_in') }}">Sign In</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

app/templates/register.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Register Page</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.first_name.label }} <br>
            {{ form.first_name(size=32) }}
            {% for error in form.first_name.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.last_name.label }} <br>
            {{ form.last_name(size=32) }}
            {% for error in form.last_name.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.username.label }} <br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }} <br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }} <br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_password.label }} <br>
            {{ form.confirm_password(size=32) }}
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.submit(class='btn btn-primary') }}
        </p>
    </form>
    
{% endblock content %}

app/templates/sign_in.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Sign In Page</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }} <br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }} <br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>
        {{ form.submit(class='btn btn-primary') }}
        </p>    
    </form>    
{% endblock content %}

app/templates/user.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>{{ user.username }}</h2>
    {% for cards in collect %}
        
        <a href="{{ url_for('collect.show_card', pokemon=cards.pokemon, username=current_user.username ) }}">{{ cards.pokemon }}</a> <br>
        
    {% endfor %}
    
    {% if data  %}
    
        <div class="card ml-50" style="width: 18rem;">
            <img src="{{ data['sprites']['front_default'] }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ data['name'] }}</h5>
                    <p class="card-text">Type: {{ types[0] }} {% if data['types'][1] %}, {{  data['types'][1]['type']['name'] }} {% else %}  {% endif %} <br>
                                        Abilities: {{ abilities[0] }} {{ abilities[1] }} <br>
                                        Stats: <br>
                                        {{ stats[0] }}: {{ base_stat[0] }} <br>
                                        {{ stats[1] }}: {{ base_stat[1] }} <br>
                                        {{ stats[2] }}: {{ base_stat[2] }} <br>
                                        {{ stats[3] }}: {{ base_stat[3] }} <br>
                                        {{ stats[4] }}: {{ base_stat[4] }} <br>
                                        {{ stats[5] }}: {{ base_stat[5] }}</p>
                                      
                </div>
            </div>
        
    {% endif %}
    
    
{% endblock %}